export const FakePartyList = [
  {
    id: 1,
    name: "Neon Night",
    ticket_price: 1000,
    currency: "RSD",
    theme: "Neon Glow",
    location: "Kralja Petra 112",
    city: "Belgrade",
    type: "House",
    description:
      "Join us for an electrifying Neon Night! Dance under UV lights, enjoy signature glowing cocktails, and feel the house beats all night long. Dress in neon colors for the full effect!",
    phone_number: "+381 64 123 4567",
    start_time: "22:00",
    end_time: "04:00",
    age_limit: 18,
    vip_conditions: "Minimum spend 10,000 RSD.",
    table_count: 0,
    capacity: 150,
    people_signed_up: 120,
    party_date: "2025-05-12",
  },
  {
    id: 2,
    name: "Retro Club Vibes",
    ticket_price: 0,
    currency: "RSD",
    theme: "80s & 90s Classics",
    location: "Tome Živanovića 15",
    city: "Belgrade",
    type: "Club",
    description:
      "Throwback to the ultimate retro party! Relive the best hits from the 80s and 90s with a funky dance floor, old-school visuals and drinks at nostalgic prices.",
    phone_number: "+381 63 987 6543",
    start_time: "21:00",
    end_time: "03:00",
    age_limit: 21,
    vip_conditions: "Minimum spend 12,000 RSD.",
    table_count: 15,
    capacity: 0,
    people_signed_up: 100,
    tables_reserved: 8,
    party_date: "2025-05-14",
  },
  {
    id: 3,
    name: "Masquerade Madness",
    ticket_price: 10,
    currency: "EUR",
    theme: "Masquerade Ball",
    location: "Kralja Petra 23",
    city: "Belgrade",
    type: "Club",
    description:
      "A night of elegance and mystery awaits! Bring your best mask and dance the night away surrounded by glamorous guests, deep house sounds and a magical atmosphere.",
    phone_number: "+381 62 321 4321",
    start_time: "23:00",
    end_time: "05:00",
    age_limit: 21,
    vip_conditions: "100 EUR minimum spend.",
    table_count: 12,
    capacity: 0,
    people_signed_up: 80,
    tables_reserved: 5,
    party_date: "2025-06-01",
  },
  {
    id: 4,
    name: "Backyard Beats",
    ticket_price: 1500,
    currency: "RSD",
    theme: "Chill & Deep House",
    location: "Kralja Petra 57",
    city: "Belgrade",
    type: "House",
    description:
      "Relaxed open-air house party with cozy lighting, live DJs, fire pits and a welcoming vibe. Perfect for summer nights with friends.",
    phone_number: "+381 61 555 6789",
    start_time: "20:00",
    end_time: "02:00",
    age_limit: 16,
    vip_conditions: "Minimum spend 8,000 RSD.",
    table_count: 0,
    capacity: 100,
    people_signed_up: 75,
    party_date: "2025-06-05",
  },
  {
    id: 5,
    name: "Electric Escape",
    ticket_price: 1200,
    currency: "RSD",
    theme: "Electronic Dance Music",
    location: "Bulevar Kralja Aleksandra 87",
    city: "Belgrade",
    type: "House",
    description:
      "Step into an electrifying atmosphere and dance till dawn. High-energy beats and immersive lights will take you on a thrilling journey.",
    phone_number: "+381 65 987 6543",
    start_time: "23:00",
    end_time: "06:00",
    age_limit: 18,
    vip_conditions: "Minimum spend 15,000 RSD.",
    table_count: 10,
    capacity: 200,
    people_signed_up: 150,
    party_date: "2025-06-10",
  },
  {
    id: 6,
    name: "Underwater Vibes",
    ticket_price: 2000,
    currency: "RSD",
    theme: "Deep Sea Glow",
    location: "Savska 21",
    city: "Belgrade",
    type: "Club",
    description:
      "Dive deep into a mesmerizing underwater-themed party. Glow in the dark and immerse yourself in a sea of beats and fun!",
    phone_number: "+381 62 123 9876",
    start_time: "22:30",
    end_time: "04:30",
    age_limit: 21,
    vip_conditions: "Minimum spend 20,000 RSD.",
    table_count: 5,
    capacity: 120,
    people_signed_up: 95,
    tables_reserved: 4,
    party_date: "2025-06-15",
  },
  {
    id: 7,
    name: "Viva La Party",
    ticket_price: 800,
    currency: "RSD",
    theme: "Latin Dance Party",
    location: "Bulevar Despota Stefana 89",
    city: "Belgrade",
    type: "Club",
    description:
      "Dance to the rhythm of Latin beats and enjoy the vibrant energy of salsa, reggaeton, and bachata all night long!",
    phone_number: "+381 64 234 5678",
    start_time: "21:00",
    end_time: "03:00",
    age_limit: 18,
    vip_conditions: "Minimum spend 10,000 RSD.",
    table_count: 8,
    capacity: 150,
    people_signed_up: 110,
    tables_reserved: 6,
    party_date: "2025-06-20",
  },
  {
    id: 8,
    name: "Rock The Night",
    ticket_price: 1500,
    currency: "RSD",
    theme: "Rock & Metal Night",
    location: "Kneza Miloša 45",
    city: "Belgrade",
    type: "Club",
    description:
      "Get ready to rock! A night of live bands, headbanging, and wild fun. Dress in black and come ready to enjoy the best rock and metal anthems.",
    phone_number: "+381 60 123 4567",
    start_time: "23:00",
    end_time: "06:00",
    age_limit: 21,
    vip_conditions: "Minimum spend 12,000 RSD.",
    table_count: 10,
    capacity: 180,
    people_signed_up: 130,
    tables_reserved: 9,
    party_date: "2025-06-25",
  },
  {
    id: 9,
    name: "Summer Breeze Festival",
    ticket_price: 1200,
    currency: "RSD",
    theme: "Festival Vibes",
    location: "Vojvode Stepe 45",
    city: "Belgrade",
    type: "Festival",
    description:
      "Experience an all-day festival with live music, food trucks, and art installations. Perfect for festival lovers and summer fun!",
    phone_number: "+381 65 432 1098",
    start_time: "14:00",
    end_time: "22:00",
    age_limit: 16,
    vip_conditions: "Free VIP entry with minimum spend of 15,000 RSD.",
    table_count: 0,
    capacity: 500,
    people_signed_up: 350,
    party_date: "2025-07-01",
  },
  {
    id: 10,
    name: "Underground Party X",
    ticket_price: 0,
    currency: "RSD",
    theme: "Underground Rave",
    location: "Kneza Miloša 112",
    city: "Belgrade",
    type: "Rave",
    description:
      "A secret underground rave with deep techno beats and a gritty, industrial vibe. Only for the brave!",
    phone_number: "+381 64 789 2345",
    start_time: "00:00",
    end_time: "06:00",
    age_limit: 18,
    vip_conditions: "VIP entry with special invite.",
    table_count: 0,
    capacity: 300,
    people_signed_up: 200,
    party_date: "2025-07-05",
  },
];
